name: forms
description: form example
version: 0.0.1
environment:
  sdk: '>=2.5.0 <3.0.0'
dependencies:
  angular: any
  angular_forms: any

dev_dependencies:
  build_runner: any
  build_test: any
  build_web_compilers: any